services:
  van-phuc-web:
    image: longnguyen1331/van-phuc-web:latest
    ports:
      - "8056:8056"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8056
      - DrCoreApi__BaseUrl=https://core.benhvien199.vn/
      - DrCoreApi__BaseUrlImage=http://localhost:8056/
      - LocalApi__BaseUrl=http://localhost:8056/api/
      - LibreOffice__SofficePath=soffice
    restart: unless-stopped
    networks:
      - drcore-network
networks:
  drcore-network:
    driver: bridge
