name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]  # Chạy khi push vào branch main
  workflow_dispatch:      # Cho phép chạy thủ công

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Get commit message
      id: commit
      run: |
        echo "message<<EOF" >> $GITHUB_OUTPUT
        git log -1 --pretty=%B >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Build and Push Admin QLCL Web Image
      if: contains(steps.commit.outputs.message, '[WEB]') || contains(steps.commit.outputs.message, '[ALL]')
      run: |
        docker build --platform linux/amd64 -t longnguyen1331/van-phuc-web:latest -f CoreAdminWeb/Dockerfile .
        docker push longnguyen1331/van-phuc-web:latest

    - name: Send Telegram notification on success
      if: success()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="✅ CI/CD build thành công DRCore Admin QLCL Web & push Docker image thành công cho repo ${{ github.repository }} commit: ${{ github.sha }}"

    - name: Send Telegram notification on failure
      if: failure()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="❌ CI/CD thất bại DRCore Admin QLCL Web cho repo ${{ github.repository }} commit: ${{ github.sha }}" 